name: macanaliz
publish_to: 'none'
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter: { sdk: flutter }
  file_picker: ^8.1.2
  dio: ^5.7.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
